### PR TITLE
Remove duplicate item.

### PR DESCRIPTION
**Pull request by isimluk**
Just look above!

### CODE REVIEW

**Comment by isimluk** [comment]
Please, enlighten me on what should I do to amend the other branch as well!

**Comment by shawndwells** [comment]
@isimluk In this case, the same control ``IR-4 (10)`` is being documented for multiple products (Tower, CoreOS, IdM). There will be similar situations where each product may have the same control response -- especially for controls that are tagged as not applicable.

**Comment by isimluk** [comment]
Yeah, I understand that. But there is duplication in each file:

https://github.com/ComplianceAsCode/redhat/blob/27a4828e01555fdd3e43550b6202a3ff9d01dbe9/ansible-tower/policies/IR-Incident_Response/component.yaml#L174-L191

It feels like copy-paste problem.

**Comment by shawndwells** [comment]
> Yeah, I understand that. But there is duplication in each file (see `IR-4 (10)` being duplicate of `IR-4 (10)`)
> 
> https://github.com/ComplianceAsCode/redhat/blob/27a4828e01555fdd3e43550b6202a3ff9d01dbe9/ansible-tower/policies/IR-Incident_Response/component.yaml#L174-L191
> 
> It feels like copy-paste problem.

Yes, you are correct. I was looking at the files in the PR vs the originals and didn't see the duplication.

**Comment by isimluk** [comment]
> Yes, you are correct. I was looking at the files in the PR vs the originals and didn't see the duplication.

This shouldn't happen again. We now have warning about this: https://github.com/isimluk/ocdb/blob/master/actions/api/components.go#L74 that is shown to user at https://github.com/isimluk/ocdb/blob/master/assets/src/app/Products/Product.tsx#L107

**Pull request merged**
