### PR TITLE
Update AC-2(1) and AC-2(3) for RHCOS

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by redhatrises** [comment]
@JAORMX for your review

**Comment by JAORMX** [comment]
@redhatrises note that this applies to creating users for openshift. These openshift users are valid for accessing RHCOS hosts (if you're an admin) if we accept some folks will be using `oc debug`. However, to configure RHCOS users (from the OS layer), the steps would be different, as we would need to configure sssd through MachineConfig. Is this a detail that should be reflected in these control responses?

**Comment by redhatrises** [comment]
> @redhatrises note that this applies to creating users for openshift. These openshift users are valid for accessing RHCOS hosts (if you're an admin) if we accept some folks will be using `oc debug`. However, to configure RHCOS users (from the OS layer), the steps would be different, as we would need to configure sssd through MachineConfig. Is this a detail that should be reflected in these control responses?

@JAORMX Good point! Is there documentation for configuring SSSD on RHCOS? I didn't think that there was.

**Comment by JAORMX** [comment]
@redhatrises there isn't as far as I've searched... we need to come up with that.

**Comment by jhrozek** [comment]
> > @redhatrises note that this applies to creating users for openshift. These openshift users are valid for accessing RHCOS hosts (if you're an admin) if we accept some folks will be using `oc debug`. However, to configure RHCOS users (from the OS layer), the steps would be different, as we would need to configure sssd through MachineConfig. Is this a detail that should be reflected in these control responses?
> 
> @JAORMX Good point! Is there documentation for configuring SSSD on RHCOS? I didn't think that there was.

There is not because on RHEL you would use imperative tools (ipa-client-install,realmd, ...) to set up the configuration of the PAM/NSS stack and SSSD itself. That's not how things are done on RHCOS where you would change the config with MachineConfig manifests. Plus, there's the "thou shalt not login to RHCOS" argument.

**Comment by carlosmmatos** [comment]
closing due to lack of responses

**Pull request closed without merging**
