### PR TITLE
ocp4 - ca-5 (all) - changing from partial to not applicable and updating narrative

### PR DESCRIPTION
**Pull request by itewk**
peer reviewed by:
* @kevindoingbizas

### CODE REVIEW

**Comment by shawndwells** [comment]
@itewk Nudge. What was your take on the PR review? Does it sound reasonable?

**Comment by itewk** [comment]
@shawndwells sounds good to me. updating now.

**Comment by itewk** [comment]
@shawndwells updated.

**Comment by redhatrises** [comment]
Updates made appropriately. Merging.

**Pull request merged**
