### PR TITLE
Deprecate this repo

### PR DESCRIPTION
**Pull request by JAORMX**
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now c7b00a1f0b4980ae5c10fef5795961199c09a016

**Comment by ggbecker** [comment]
Maybe we should use github's function to archive the project, just an idea.

**Review by jhrozek — COMMENTED** [review]
I agree with deprecating the repo. Would you mind pointing to some example rules in the new format in the CaC repo so that they are easier for everyone to find?

**Comment by JAORMX** [comment]
@ggbecker I don't have the admin rights to archive this. Feel free to do so

**Comment by ggbecker** [comment]
> @ggbecker I don't have the admin rights to archive this. Feel free to do so

Neither do I. Let me ask someone who has it.

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now a3d5e2c415920debe461233ddcf00adc2ec244c5

**Comment by JAORMX** [comment]
> I agree with deprecating the repo. Would you mind pointing to some example rules in the new format in the CaC repo so that they are easier for everyone to find?

done

**Comment by yuumasato** [comment]
@JAORMX Does it make sense to delete stuff?
We could just update the README with info before archiving it.

**Comment by JAORMX** [comment]
> @JAORMX Does it make sense to delete stuff? We could just update the README with info before archiving it.

It's in Git, it's recoverable. If folks would prefer that I don't delete this, and just change the README, I could do that.

**Review by jhrozek — APPROVED** [review]
thanks, I'm happy now

**Comment by yuumasato** [comment]
It sure is recoverable.

Do you think there is a risk that the deprecation/archived state could go unnoticed?

**Review by yuumasato — APPROVED** [review]

**Comment by yuumasato** [comment]
@JAORMX maybe using the label is not a good idea, it may not last forever

**Comment by ggbecker** [comment]
Do we know how https://atopathways.redhatgov.io/ uses the content of this project? maybe there is some kind of automation that would break the website, I don't know. I prefer keeping the original content, even the README and only prepending the deprecation notice to the README. Then we go and archive the project.

I see this as the less intrusive way of deprecating a repo.

**Comment by JAORMX** [comment]
@ggbecker could you push a PR to deprecate this? I'm about to enter a meeting frenzy.

**Comment by michaelepley** [comment]
> Do we know how https://atopathways.redhatgov.io/ uses the content of this project? 
It pulls all content into an in-memory database, processes some opencontrol templates, and displays the data. Updates occur on a nighty schedule. We would like to maintian the repo just to drive this process until we have a transition plan for the site.

**Comment by ggbecker** [comment]
Do we plan to update the contents of this repo? If no, then we can still archive which makes the repo read-only thus not breaking the workflow.

**Comment by JAORMX** [comment]
@ggbecker let's archive it then

**Comment by JAORMX** [comment]
I would advice folks to stop updating this repo and focus on CaC/content instead

**Comment by ggbecker** [comment]
> @ggbecker let's archive it then

The readme has been updated here https://github.com/ComplianceAsCode/redhat/pull/1356 after merging that we can then archive it.

**Pull request closed without merging**
