### PR TITLE
Validate opencontrol content

### PR DESCRIPTION
**Pull request by isimluk**
So we avoid, duplicates and other issues.

### CODE REVIEW

**Comment by shawndwells** [comment]
nice!! thank you for this!

**Comment by isimluk** [comment]
> nice!! thank you for this!

Thanks, it finally works:
```
Satisfy 'SA-9 (1)': Duplicate narratives sequence: a
Found duplicate item: SA-15 (4)
Found duplicate item: SI-7 (11)
Satisfy 'SA-9 (1)': Duplicate narratives sequence: a
Found duplicate item: SA-15 (4)
Found duplicate item: SI-2 (1)
Found duplicate item: SI-7 (11)
##[error]Process completed with exit code 7.
```

See https://github.com/ComplianceAsCode/redhat/runs/438820294?check_suite_focus=true

Most of the errors should be fixed with https://github.com/ComplianceAsCode/redhat/pull/1129

**Comment by isimluk** [comment]
I think we can merge this now, to see failures/passes on subsequent PRs.

**Comment by isimluk** [comment]
It now passes. Life is great!

**Comment by redhatrises** [comment]
We definitely need this. Ack.

**Pull request merged**
