### PR TITLE
OCP4: Update the response to RA-5

### PR DESCRIPTION
**Pull request by JAORMX**
The Compliance Operator is the answer.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
@carlosmmatos @jhrozek @mrogers950 PTAL

**Comment by jhrozek** [comment]
In general, I think mentioning CO is a good idea. Though I would be interested in hearing from @carlosmmatos what does the control typically mean when it says "vulnerability". CO can be though of as a hardening tool, but it doesn't scan for CVEs (yet?).
Also, why not use the same reply for a) ?

Finally, what's the deal with the Jira tickets, can we remove/close them as we go through the controls?

**Comment by jhrozek** [comment]
> Finally, what's the deal with the Jira tickets, can we remove/close them as we go through the controls?
Oh, I see that Ozz at least added a comment, great.

**Comment by JAORMX** [comment]
@jhrozek a misconfiguration can be considered a vulnerability and is explicitly mentioned in the control. That's why I decided to go forward and put CO as the component that addresses the control.

**Comment by JAORMX** [comment]
@jhrozek note that a) is an organizational control and hence we don't need to address it.

**Comment by JAORMX** [comment]
Note:

A Fix for the Compliance Operator is needed: https://github.com/openshift/compliance-operator/pull/638
And here's the control check: https://github.com/ComplianceAsCode/content/pull/6957

**Comment by carlosmmatos** [comment]
@JAORMX @jhrozek I would say that this is probably partially correct.. CO does address misconfiguration as stated in that control:
```Enumerating platforms, software flaws, and improper configurations;```

And vulnerability is a loose term nowadays so unless they are specifically talking about CVE's (which they aren't), we can use CO as part of the solution. The other part will probably be ACS - just need to get the verbiage around that.

Thoughts?

**Comment by JAORMX** [comment]
> @JAORMX @jhrozek I would say that this is probably partially correct.. CO does address misconfiguration as stated in that control:
> `Enumerating platforms, software flaws, and improper configurations;`
> 
> And vulnerability is a loose term nowadays so unless they are specifically talking about CVE's (which they aren't), we can use CO as part of the solution. The other part will probably be ACS - just need to get the verbiage around that.
> 
> Thoughts?

sounds good to me. Can this be done in another PR? (The ACS addition)

**Comment by carlosmmatos** [comment]
> > @JAORMX @jhrozek I would say that this is probably partially correct.. CO does address misconfiguration as stated in that control:
> > `Enumerating platforms, software flaws, and improper configurations;`
> > And vulnerability is a loose term nowadays so unless they are specifically talking about CVE's (which they aren't), we can use CO as part of the solution. The other part will probably be ACS - just need to get the verbiage around that.
> > Thoughts?
> 
> sounds good to me. Can this be done in another PR? (The ACS addition)

Absolutely!

**Pull request merged**
