### PR TITLE
ocp4 - AC-2 (1) - mark as complete and update narrative

### PR DESCRIPTION
**Pull request by itewk**
Peer reviewed by:
* @kevindoingbizas

### CODE REVIEW

**Comment by redhatrises** [comment]
@itewk we should keep some of the following verbage `such as an Identity Provider (IdP), Active Directory (MSAD), LDAP, etc.`

**Comment by itewk** [comment]
@redhatrises updated.

**Comment by redhatrises** [comment]
@itewk thanks! Would it make sense to add the following:

```
To configure an IdP, see https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-ldap-identity-provider.html#configuring-ldap-identity-provider
```

Feels like a great way to complete the narrative. Thoughts?

**Comment by itewk** [comment]
@redhatrises wasn't sure if we should put doc links in? If we should then only suggestion would be to swap out `4.3` for `latest`

**Comment by redhatrises** [comment]
> @redhatrises wasn't sure if we should put doc links in? If we should then only suggestion would be to swap out `4.3` for `latest`

I think we should... I our many customers would be appreciative of these things. Also, using `latest` is a great suggestion!

**Comment by itewk** [comment]
@redhatrises updated PR, but is there a special syntax to get ATOpathways to pick it up as a link and to get stickler-ci to not be annoyed?

**Comment by itewk** [comment]
@redhatrises i really hate that when you edit it auto adds in the whitespace and then stickler doesn't like it....

**Comment by redhatrises** [comment]
> @redhatrises i really hate that when you edit it auto adds in the whitespace and then stickler doesn't like it....

<joke>But... it's sooo pretty without whitespace</joke>

**Comment by redhatrises** [comment]
LGTM

**Pull request merged**
